// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'current_percent': string;
  'ex_seek_input': string;
  'input': string;
  'length': string;
  'percent': string;
  'played': string;
  'seek': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
