// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'text--align--center': string;
  'text--align--left': string;
  'text--align--right': string;
  'text--color--accent': string;
  'text--color--blue': string;
  'text--color--green': string;
  'text--color--green-alert': string;
  'text--color--grey': string;
  'text--color--grey-o50': string;
  'text--color--grey-o64': string;
  'text--color--primary': string;
  'text--color--white': string;
  'text--color--yellow': string;
  'text--family--inter-bold': string;
  'text--family--inter-medium': string;
  'text--family--inter-regular': string;
  'text--family--inter-semi-bold': string;
  'text--family--pt-bold': string;
  'text--family--pt-regular': string;
  'text--type--s12px-h14px': string;
  'text--type--s12px-h18px': string;
  'text--type--s14px-h24px': string;
  'text--type--s16px-h18px': string;
  'text--type--s16px-h24px': string;
  'text--type--s18px-h20px': string;
  'text--type--s18px-h24px': string;
  'text--type--s24px-h26px': string;
  'text--type--s32px-h36px': string;
  'text--type--s48px-h54px': string;
}
export const cssExports: CssExports;
export default cssExports;
