// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'left_side': string;
  'logotype': string;
  'logotype_img': string;
}
export const cssExports: CssExports;
export default cssExports;
