// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'hide': string;
  'options': string;
  'select': string;
  'select_container': string;
  'select_containerActive': string;
  'text': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
