// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fluid': string;
  'size': string;
  'size--large': string;
  'size--small': string;
  'theme': string;
  'theme--green': string;
  'theme--grey': string;
  'theme--light': string;
  'theme--none': string;
}
export const cssExports: CssExports;
export default cssExports;
