// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'check': string;
  'check_ico': string;
  'check_ico_active': string;
  'option': string;
}
export const cssExports: CssExports;
export default cssExports;
