// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loader': string;
  'loader_4': string;
  'loader_container': string;
  'loader_content': string;
  'stage': string;
}
export const cssExports: CssExports;
export default cssExports;
