// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'td_child': string;
  'text': string;
  'th_child': string;
  'tr_background': string;
  'tr_child': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
