// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ico': string;
  'title': string;
  'title_link': string;
  'upload': string;
}
export const cssExports: CssExports;
export default cssExports;
