// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'emu_btn': string;
  'file_name': string;
  'hiden': string;
  'ico_upload': string;
  'ico_upload_brake': string;
  'preview': string;
  'text': string;
  'upload': string;
  'uploaded': string;
}
export const cssExports: CssExports;
export default cssExports;
