// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controller': string;
  'ex_seek_input': string;
  'ex_valume_input': string;
  'input': string;
  'length': string;
  'played': string;
  'player': string;
  'playerActive': string;
  'seek': string;
  'volume': string;
  'volume_container': string;
  'volume_input': string;
}
export const cssExports: CssExports;
export default cssExports;
