// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'billing': string;
  'link': string;
  'token_copy': string;
}
export const cssExports: CssExports;
export default cssExports;
