// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'content': string;
  'contentActive': string;
  'header': string;
  'modal': string;
  'modalActive': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
