// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'dropDown': string;
  'dropDownActive': string;
  'dropDown_overviwe': string;
  'dropDown_overviweActive': string;
  'triangle': string;
}
export const cssExports: CssExports;
export default cssExports;
