// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'nav_link_active': string;
  'navigation': string;
}
export const cssExports: CssExports;
export default cssExports;
