// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gradient': string;
  'skeleton': string;
}
export const cssExports: CssExports;
export default cssExports;
