// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fadein': string;
  'helper_example': string;
  'helper_example_active': string;
  'placeholder': string;
  'placeholder_active': string;
  'text_input': string;
  'text_input_container': string;
  'valid': string;
  'valid_active': string;
  'valid_err_active': string;
}
export const cssExports: CssExports;
export default cssExports;
