// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checked': string;
  'deprecated': string;
  'detected': string;
  'fail': string;
  'pending': string;
  'status_container': string;
  'status_flag': string;
  'success': string;
  'unknown': string;
}
export const cssExports: CssExports;
export default cssExports;
