// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'checkmark': string;
  'container': string;
}
export const cssExports: CssExports;
export default cssExports;
